"""TIMESTAMPS now UTC

Revision ID: 2051fb9fa2da
Revises: 36ad85a0410a
Create Date: 2025-03-14 06:16:32.047198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2051fb9fa2da'
down_revision: Union[str, None] = '36ad85a0410a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text("'2025-03-14 06:16:25.785982'::timestamp without time zone"))
    op.alter_column('festivals', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text("'2025-03-14 06:16:25.785982'::timestamp without time zone"))
    op.alter_column('tracks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text("'2025-03-14 06:16:25.785982'::timestamp without time zone"))
    op.alter_column('users', 'token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text("'2025-03-14 06:16:25.785982'::timestamp without time zone"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text("'2025-03-14 06:16:25.785982'::timestamp without time zone"))
    op.alter_column('users', 'token_expires_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tracks', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text("'2025-03-14 06:16:25.785982'::timestamp without time zone"))
    op.alter_column('festivals', 'last_updated',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text("'2025-03-14 06:16:25.785982'::timestamp without time zone"))
    op.alter_column('artists', 'last_updated',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text("'2025-03-14 06:16:25.785982'::timestamp without time zone"))
    # ### end Alembic commands ###
