"""Tweaks to models

Revision ID: 7d4f3a37fba5
Revises: 2051fb9fa2da
Create Date: 2025-03-15 05:40:16.671880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4f3a37fba5'
down_revision: Union[str, None] = '2051fb9fa2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('festivals', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('uq_user_artist_timeframe', 'user_artists', ['user_id', 'artist_id', 'timeframe'])
    op.add_column('users', sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_constraint('uq_user_artist_timeframe', 'user_artists', type_='unique')
    op.drop_column('festivals', 'created_at')
    # ### end Alembic commands ###
